### ISSUE TITLE
dbConnect() give a warning message when connecting to a MS Access data base

### ISSUE THREAD

**Issue by andresrcs** [rstats-db/odbc#107] opened 2017-08-27 02:43 UTC
### Issue Description and Expected Result
When I create a connection I get the warning message below, and the "Connections" panel of RStudio 1.1.345 doesn't recognise it.

`warning messages from top-level task callback '1'
Warning message:
Could not notify connection observer. nanodbc/nanodbc.cpp:4274: HYC00: [Microsoft][Controlador ODBC Microsoft Access]Función opcional no implementada `

Nevertheless, I can use the connection for querying the data base without any problem.

### Database
Microsoft Access 2016

### Reproducible Example
[test.accdb](https://www.dropbox.com/s/hlvz00babvy7qur/test.accdb?dl=0)
```r
library(odbc)
library(DBI)
con <- dbConnect(odbc::odbc(), .connection_string = "Driver={Microsoft Access Driver (*.mdb, *.accdb)};Dbq=./test.accdb")
warning messages from top-level task callback '1'
Warning message:
Could not notify connection observer. nanodbc/nanodbc.cpp:4274: HYC00: [Microsoft][Controlador ODBC Microsoft Access]Función opcional no implementada
```

<details>
<summary>Session Info</summary>

```r
devtools::session_info()
Session info --------------------------------------------------------------------
 setting  value                       
 version  R version 3.4.1 (2017-06-30)
 system   x86_64, mingw32             
 ui       RStudio (1.1.345)           
 language (EN)                        
 collate  Spanish_Peru.1252           
 tz       America/Bogota              
 date     2017-08-26                  

Packages ------------------------------------------------------------------------
 package   * version date       source        
 base      * 3.4.0   2017-04-21 local         
 bit         1.1-12  2014-04-09 CRAN (R 3.4.0)
 bit64       0.9-7   2017-05-08 CRAN (R 3.4.0)
 blob        1.1.0   2017-06-17 CRAN (R 3.4.0)
 compiler    3.4.0   2017-04-21 local         
 datasets  * 3.4.0   2017-04-21 local         
 DBI       * 0.7     2017-06-18 CRAN (R 3.4.0)
 devtools    1.13.3  2017-08-02 CRAN (R 3.4.1)
 digest      0.6.12  2017-01-27 CRAN (R 3.4.0)
 graphics  * 3.4.0   2017-04-21 local         
 grDevices * 3.4.0   2017-04-21 local         
 hms         0.3     2016-11-22 CRAN (R 3.4.0)
 memoise     1.1.0   2017-04-21 CRAN (R 3.4.0)
 methods   * 3.4.0   2017-04-21 local         
 odbc        1.1.1   2017-06-27 CRAN (R 3.4.1)
 Rcpp        0.12.12 2017-07-15 CRAN (R 3.4.1)
 rlang       0.1.2   2017-08-09 CRAN (R 3.4.1)
 stats     * 3.4.0   2017-04-21 local         
 tibble      1.3.4   2017-08-22 CRAN (R 3.4.1)
 tools       3.4.0   2017-04-21 local         
 utils     * 3.4.0   2017-04-21 local         
 withr       2.0.0   2017-07-28 CRAN (R 3.4.1)
 yaml        2.1.14  2016-11-12 CRAN (R 3.4.0)
```
</details>

**Comment by jimhester** [comment] 2017-08-27 12:05
Please try with the current devel version, it should be fixed there.

```r
devtools::install_github("odbc")
```

Partial duplicate of https://github.com/rstats-db/odbc/issues/98, https://github.com/rstats-db/odbc/issues/103

**Closed by jimhester** 2017-08-27 12:05 UTC

**Comment by andresrcs** [comment] 2017-08-27 14:15
Thanks, but actually this command is what works for me
```r
devtools::install_github("rstats-db/odbc")
