### ISSUE TITLE
Problem retrieving bigint value from SQL Server

### ISSUE THREAD

**Issue by hemip** [rstats-db/odbc#35] opened 2017-03-08 14:55 UTC
### Problem retrieving bigint values

I was bit by a bug when testing out the odbc-package. I couldn't understand why my joins in dplyr didn't work as expected. After a while I found out that the type casting of bigint values didn't work as expected. Below is an example from our in house database, and a comparison with RSQLServer. 

### Database
SQL Server 2012

### Non-reproducible example
```r
library(odbc)
library(DBI)

# Using odbc
dbConnect(odbc::odbc(),"rt; UID=xxxxx; PWD=yyyyy") -> db
dbGetQuery(db,"USE RT; SELECT TOP 1 DelytaID, CAST(DelytaID AS char) AS DelytaCAST FROM dbo.vy_Delyteregister")
# Output
#     DelytaID  DelytaCAST
# 1 -603275544 81001103080                   

# Using RSQLServer
dbConnect(RSQLServer::SQLServer(),"RT") -> db
dbGetQuery(db,"USE RT; SELECT TOP 1 DelytaID, CAST(DelytaID AS char) AS DelytaCAST FROM dbo.vy_Delyteregister")
# Output
#      DelytaID  DelytaCAST
# 1 81001103080 81001103080 
```
<details>
<summary>Session Info</summary>

```r
devtools::session_info()
#Session info #-------------------------------------------------------------------------------------------------
#setting  value                       
# version  R version 3.3.2 (2016-10-31)
# system   x86_64, darwin13.4.0        
# ui       RStudio (1.0.136)           
# language (EN)                        
# collate  sv_SE.UTF-8                 
# tz       Europe/Stockholm            
# date     2017-03-08    

# odbc         1.0.1      2017-02-17 Github (rstats-db/odbc@8abb2ab) 
# RSQLServer   0.2.099    2016-09-28 Github (imanuelcostigan/RSQLServer@0b16383)
```
</details>

**Comment by jimhester** [comment] 2017-04-04 19:13
Closing as a duplicate of https://github.com/rstats-db/odbc/issues/9, we will have true 64 bit support in the near future however!

**Closed by jimhester** 2017-04-04 19:13 UTC
