### ISSUE TITLE
top-level task callback '1' ... feature not implemented

### ISSUE THREAD

**Issue by timothyslau** [rstats-db/odbc#109] opened 2017-09-06 18:40 UTC
### Issue Description and Expected Result
I can't create a connection to an Oracle database.

### Database
Oracle Version: 11.02.0040

### Reproducible Example
This:
```
DBI::dbConnect(drv = odbc::odbc(),
dsn = "",
host = "",
database = "",
uid = "",
pwd = "",
port = "")

```
produces the following:
```
<OdbcConnection> uid@db
Oracle Version: 11.02.0040

```
While This:
```
con <- DBI::dbConnect(drv = odbc::odbc(),
dsn = "",
host = "",
database = "",
uid = "",
pwd = "",
port = "")

```
Produces the following:
```
warning messages from top-level task callback '1'
Warning message:
Could not notify connection observer. nanodbc/nanodbc.cpp:4274: HYC00: [Oracle][ODBC]Optional feature not implemented.

```

I don't know what's wrong. Any help is appreciated.

**Comment by jimhester** [comment] 2017-09-06 18:49
Please try with the current devel version of the IDE

```r
devtools::install_github("rstats-db/odbc")
```

Duplicate of https://github.com/rstats-db/odbc/issues/103, https://github.com/rstats-db/odbc/issues/107

**Closed by jimhester** 2017-09-06 18:49 UTC

**Comment by timothyslau** [comment] 2017-09-06 21:38
It conects but only shows some of the tables. When I try to connect to some of the tables I see in Toad it gives:

```
Error: <SQL> 'SELECT * FROM schema.table'
  nanodbc/nanodbc.cpp:1587: HY000: [Oracle][ODBC][Ora]ORA-01031: insufficient privileges
```
