### ISSUE TITLE
dbBind on SQL Server

### ISSUE THREAD

**Issue by ajholguin** [rstats-db/odbc#28] opened 2017-02-16 19:47 UTC
### Issue Description and Expected Result
parameterized queries using dbBind() and dbFetch() produce nanodbc error:

```r
Error in result_fetch(res@ptr, n, ...) : 
  nanodbc.cpp:2517: 24000: [Microsoft][ODBC Driver 13 for SQL Server]Invalid cursor state
```

### Database
Microsoft SQL Server 2016 (SP1) (KB3182545) - 13.0.4001.0 (X64)

### Reproducible Example

Example (from #19, but using SQL Server):
```r
library(DBI)
con <- dbConnect(odbc::odbc(), "sql_server_test")
dbWriteTable(con, "iris", iris)
iris_result <- dbSendQuery(con, "SELECT * FROM iris WHERE 'Petal.Width' > ?")
dbBind(iris_result, list(2.3))
dbFetch(iris_result)
dbBind(iris_result, list(2.4))
dbFetch(iris_result)
dbClearResult(iris_result)
dbDisconnect(con)
```

<details>
<summary>Session Info</summary>

```r
devtools::session_info()
Session info ---------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.3.1 (2016-06-21)
 system   x86_64, mingw32             
 ui       RStudio (1.0.136)           
 language (EN)                        
 collate  English_United States.1252  
 tz       America/Los_Angeles         
 date     2017-02-16                  

Packages -------------------------------------------------------------------------------------------------------
 package    * version    date       source                      
 assertthat   0.1        2013-12-06 CRAN (R 3.3.2)              
 blob         1.0.0.9000 2017-01-30 Github (hadley/blob@389065e)
 DBI        * 0.5-1      2016-09-10 CRAN (R 3.3.2)              
 devtools     1.12.0     2016-06-24 CRAN (R 3.3.2)              
 digest       0.6.12     2017-01-27 CRAN (R 3.3.2)              
 memoise      1.0.0      2016-01-29 CRAN (R 3.3.2)              
 odbc         1.0.1      2017-02-07 CRAN (R 3.3.1)              
 Rcpp         0.12.9     2017-01-14 CRAN (R 3.3.2)              
 tibble       1.2        2016-08-26 CRAN (R 3.3.2)              
 withr        1.0.2      2016-06-20 CRAN (R 3.3.2)
```
</details>

**Comment by jimhester** [comment] 2017-04-21 16:36
I can reproduce this but do not yet know the exact cause or a solution

**Comment by nwstephens** [comment] 2017-06-19 19:27
Magnitude wrote back: I have tried running the script that was reported on github using RStudio (R 3.4.0). I am not able to reproduce the problem. The error I'm getting is HY010: [Microsoft][ODBC Driver Manager] Function sequence error which is coming from the driver manager and has nothing to do with the driver. Following the similar steps in ODBC is not causing any issues. Were you also able to reproduce the problem and getting the cursor error? Currently without the driver logs I am unable to investigate further. If you are getting cursor error then I can try to retrace the steps from the logs and see if I'm also hitting it in ODBCtest.

**Comment by jimhester** [comment] 2017-06-20 15:22
As of https://github.com/rstats-db/odbc/commit/0d196d5c42a6b513513c2fe5efc280fe044ba0cc this should be fixed. One slight tweak is SQL Server uses double quotes rather than single quotes to quote identifiers, but with that change everything is now working. @nwstephens I think we can close the magnitude ticket for this as well.

``` r
library(DBI);con <- dbConnect(odbc::odbc(), "SQLServer2", UID = 'testuser', PWD = 'test');
dbWriteTable(con, "iris", iris)
iris_result <- dbSendQuery(con, "SELECT * FROM iris WHERE \"Petal.Width\" > ?")
dbBind(iris_result, list(2.3))
dbFetch(iris_result)
#>   Sepal.Length Sepal.Width Petal.Length Petal.Width   Species
#> 1          6.3         3.3          6.0         2.5 virginica
#> 2          7.2         3.6          6.1         2.5 virginica
#> 3          5.8         2.8          5.1         2.4 virginica
#> 4          6.3         3.4          5.6         2.4 virginica
#> 5          6.7         3.1          5.6         2.4 virginica
#> 6          6.7         3.3          5.7         2.5 virginica
dbBind(iris_result, list(2.4))
dbFetch(iris_result)
#>   Sepal.Length Sepal.Width Petal.Length Petal.Width   Species
#> 1          6.3         3.3          6.0         2.5 virginica
#> 2          7.2         3.6          6.1         2.5 virginica
#> 3          6.7         3.3          5.7         2.5 virginica
dbClearResult(iris_result)
dbDisconnect(con)
```

**Closed by jimhester** 2017-06-20 15:22 UTC
Labels: bug
