### ISSUE TITLE
select queries are faster with the RODBC package on Hadoop databases

### ISSUE THREAD

**Issue by aschmu** [rstats-db/odbc#27] opened 2017-02-13 11:04 UTC
### Impala/Hive queries faster when using RODBC
This isn't a bug per say. However I've noticed that  `dbGetQuery()` type queries are consistently slower on Hadoop (at least on our installation).

### Database
Cloudera Impala CDH 5.7.1 and Cloudera Hive CDH 5.7..1

### Reproducible Example

I cannot produce a fully reproducible example since to my knowledege DBI doesn't provide standard Hive/Impala tables that can be tested with minimal work. I can say however that I have seen substantial (up to 3x times faster) on select queries using a Teradata database when using `odbc` in place of `RODBC`. Maybe there's something particular in how Hive/impala queries are handled that's not reflected in `odbc`'s current implementation.

Example:
```r
library(RODBC)
library(microbenchmark)
library(odbc)

conn_impala <- odbcConnect("ODBC-Impala-XXXX")
conn_impala_dbi <- dbConnect(odbc::odbc(), "ODBC-Impala-XXXX")
query_impala <- "select * from database.logs where part_date = '2016-12-15' limit 1000000"
microbenchmark(
  odbc = res_odbc_impala <- dbGetQuery(conn = conn_impala_dbi, query_impala),
  rodbc = res_RODBC_impala <- sqlQuery(channel = conn_impala, query_impala),
  times = 1L
)

  expr      min       lq     mean   median       uq      max neval
  odbc 403.3625 403.3625 403.3625 403.3625 403.3625 403.3625     1
 rodbc 152.5502 152.5502 152.5502 152.5502 152.5502 152.5502     1
```
Btw, the query is long enough that it's not affected by random variations.

<details>
<summary>Session Info</summary>

```r
devtools::session_info()
#> Unit: seconds
Session info ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.3.1 (2016-06-21)
 system   x86_64, linux-gnu           
 ui       RStudio (1.0.136)           
 language (EN)                        
 collate  fr_FR.UTF-8                 
 tz       Europe/Paris                
 date     2017-02-13                  

Packages -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 package        * version    date       source                        
 assertthat       0.1        2013-12-06 CRAN (R 3.3.1)                
 blob             0.0.0.9000 2016-12-13 Github (hadley/blob@f1d4bf7)  
 codetools        0.2-14     2015-07-15 CRAN (R 3.3.1)                
 colorspace       1.3-1      2016-11-18 CRAN (R 3.3.1)                
 DBI              0.5-13     2016-12-13 Github (rstats-db/DBI@238b676)
 devtools         1.12.0     2016-06-24 CRAN (R 3.3.1)                
 digest           0.6.10     2016-08-02 CRAN (R 3.3.1)                
 ggplot2          2.2.0      2016-11-11 CRAN (R 3.3.1)                
 gtable           0.2.0      2016-02-26 CRAN (R 3.3.1)                
 httr             1.2.1      2016-07-03 CRAN (R 3.3.1)                
 lattice          0.20-33    2015-07-14 CRAN (R 3.3.1)                
 lazyeval         0.2.0      2016-06-12 CRAN (R 3.3.1)                
 MASS             7.3-45     2016-04-21 CRAN (R 3.3.1)                
 Matrix           1.2-6      2016-05-02 CRAN (R 3.3.1)                
 memoise          1.0.0      2016-01-29 CRAN (R 3.3.1)                
 microbenchmark * 1.4-2.1    2015-11-25 CRAN (R 3.3.1)                
 multcomp         1.4-6      2016-07-14 CRAN (R 3.3.1)                
 munsell          0.4.3      2016-02-13 CRAN (R 3.3.1)                
 mvtnorm          1.0-5      2016-02-02 CRAN (R 3.3.1)                
 odbc           * 1.0.0      2017-02-05 CRAN (R 3.3.1)                
 plyr             1.8.4      2016-06-08 CRAN (R 3.3.1)                
 R6               2.2.0      2016-10-05 CRAN (R 3.3.1)                
 Rcpp             0.12.8     2016-11-17 CRAN (R 3.3.1)                
 RODBC          * 1.3-14     2016-09-26 CRAN (R 3.3.1)                
 rsconnect        0.6        2016-11-21 CRAN (R 3.3.1)                
 sandwich         2.3-4      2015-09-24 CRAN (R 3.3.1)                
 scales           0.4.1      2016-11-09 CRAN (R 3.3.1)                
 survival         2.40-1     2016-10-30 CRAN (R 3.3.1)                
 TH.data          1.0-7      2016-01-28 CRAN (R 3.3.1)                
 tibble           1.2        2016-08-26 CRAN (R 3.3.1)                
 withr            1.0.2      2016-06-20 CRAN (R 3.3.1)                
 zoo              1.7-13     2016-05-03 CRAN (R 3.3.1)  
```
</details>

**Comment by jimhester** [comment] 2017-02-14 14:49
I cannot reproduce these results using a simple 1 node cluster loaded with a dataset from http://www.andresmh.com/nyctaxitrips/

```r
library(DBI)
library(RODBC)
con_odbc <- dbConnect(odbc::odbc(), "Impala")
con_rodbc <- odbcConnect("Impala")
sql <- "SELECT pickup_datetime from test where pickup_datetime > '2013-01-05'"
microbenchmark(times = 3,
  odbc = system.time(res <- dbGetQuery(con_odbc, sql)),
  RODBC = system.time(res2 <- sqlQuery(con_rodbc, sql)))
#> Unit: seconds
#>   expr       min        lq      mean    median        uq       max neval
#>   odbc  5.562133  5.572844  5.580854  5.583555  5.590215  5.596874     3
#>  RODBC 17.609515 17.622082 17.644284 17.634650 17.661668 17.688687     3
dim(res)
#> [1] 983010      1
dim(res2)
#> [1] 983010      1
```

Maybe the issue only arises on non-trivial clusters, or perhaps this is a data locality/caching issue, does reversing the order you run the queries (run RODBC first) change the results?

**Comment by aschmu** [comment] 2017-02-16 11:49
Thanks for looking into this. I tried the same benchmark on another computer (and not part of the hadoop cluster) and odbc was consistently faster than RODBC this time. 
Reversing the order didn't do anything however using the initial client (a linux VM). I'll ask my sysadmin if there's something peculiar about the VM config.

**Comment by jimhester** [comment] 2017-02-22 15:31
I am going to close this for now, If you are able to figure out what in your setup is causing the performance degradation comment here and we can re-open this and try to sort it out.

**Closed by jimhester** 2017-02-22 15:31 UTC
